{\rtf1\ansi\ansicpg1252\cocoartf2761
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 .AppleSystemUIFontMonospaced-Regular;}
{\colortbl;\red255\green255\blue255;\red155\green162\blue177;}
{\*\expandedcolortbl;;\cssrgb\c67059\c69804\c74902;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs26 \cf2 name: egta-kd\
channels:\
  - pytorch\
  - defaults\
dependencies:\
  - python=3.8\
  - pip\
  - pytorch=1.12.1\
  - torchvision=0.13.1\
  - cudatoolkit=11.3\
  - numpy\
  - scikit-learn\
  - scikit-image\
  - matplotlib\
  - opencv-python\
  - simpleitk\
  - tqdm\
  - pip:\
      - transformers==4.30.2\
      - einops\
      - ftfy\
      - regex\
      - sentencepiece\
      - pudb\
      - wandb\
      - -e git+https://github.com/openai/CLIP.git@main#egg=clip\
      - -e .}